service: visit-counter
runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /.*
    script: main.app

instance_class: F1

automatic_scaling:
  max_instances: 1
  target_cpu_utilization: 0.9