service: default
runtime: python39

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto

instance_class: F1

automatic_scaling:
  max_instances: 1
  target_cpu_utilization: 0.9